Ec2Instance:
  Type: AWS::EC2::Instance
  Properties:
    AvailabilityZone: us-east-1a
    ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", "UBU22"]
"Mappings" : {
  "RegionMap" : {
    "us-east-1"      : { "UBU22" : "ami-0c7217cdde317cfec"},
    "us-west-1"      : { "UBU22" : "mi-0ce2cb35386fc22e9"},
    "eu-east-2"      : { "UBU22" : "ami-05fb0b8c1424f266b"},
  }
}
mysql-server:
  Type: AWS::EC2::Instance
  Properties:
    KeyName: !Ref KeyName
    SecurityGroups:
      - !Ref Ec2SecurityGroup
    UserData:
      Fn::Base64:
        Fn::Join:
          - ":"
          - - "PORT=80"
            - "TOPIC="
            - !Ref MySNSTopic
    InstanceType: aa.size
    AvailabilityZone: aa-example-1a
    ImageId: ami-1234567890abcdef0
    Volumes:
      - VolumeId: !Ref MyVolumeResource
        Device: "/dev/sdk"
    Tags:
      - Key: Name
        Value: MyTag